/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable.h>
#include <SPI.h>
#include <SPI_SPI_UART.h>
#include <SPI_PINS.h>
#include <SPI_SPI_UART_PVT.h>
#include <SPI_PVT.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <isr_SPI.h>
#include <isr_UART.h>
#include <SPI_ss_s.h>
#include <SPI_ss_s_aliases.h>
#include <SPI_miso_s.h>
#include <SPI_miso_s_aliases.h>
#include <SPI_sclk_s.h>
#include <SPI_sclk_s_aliases.h>
#include <SPI_mosi_s.h>
#include <SPI_mosi_s_aliases.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

